### ISSUE TITLE
Create "Valid reasons not to attend a MIAM" page

### ISSUE THREAD

**Issue by solidgoldpig** [ministryofjustice/c100-application#185]
https://docs.google.com/presentation/d/1XQ95gdNPOPxjJo_l3SI376JEMgE4QW3fRhWX8v0RECE/edit#slide=id.g33472dc77e_0_364

Requires list of exemptions to be complete and fixed

**Comment by zheileman** [comment]
Hi @solidgoldpig,

We have the page, but it requires to be updated with the actual copy and nice markup. It is at http://localhost:3000/miam_exemptions

(in the codebase it is `/app/views/home/miam_exemptions.en.html.erb`)
(no need to be localised to `en.yml` as it is a translated, static view)

We were waiting for the final copy and layout to be completed before updating this. Let me know if you need anything with this.

**Comment by solidgoldpig** [comment]
When I said "create", I meant that the current copy and structure needs to be slashed and burned - I see that the page itself already exists ;)

**Comment by zheileman** [comment]
Fixed in #293 (and lots of copy changes in other follow-up PRs)
