### ISSUE TITLE
Remove subsidiary questions from duty-free style nudge pages

### ISSUE THREAD

**Issue by solidgoldpig** [ministryofjustice/c100-application#193]
https://docs.google.com/presentation/d/1XQ95gdNPOPxjJo_l3SI376JEMgE4QW3fRhWX8v0RECE/edit#slide=id.g33472dc77e_0_223

https://docs.google.com/presentation/d/1XQ95gdNPOPxjJo_l3SI376JEMgE4QW3fRhWX8v0RECE/edit#slide=id.g33472dc77e_0_268

https://docs.google.com/presentation/d/1XQ95gdNPOPxjJo_l3SI376JEMgE4QW3fRhWX8v0RECE/edit#slide=id.g33472dc77e_0_273

**Comment by zheileman** [comment]
Nothing to do in the Rails app, as this was never implemented in first place. Win!
