### ISSUE TITLE
Provide details of nearest court on urgent hearing page

### ISSUE THREAD

**Issue by solidgoldpig** [ministryofjustice/c100-application#203]
https://docs.google.com/presentation/d/1XQ95gdNPOPxjJo_l3SI376JEMgE4QW3fRhWX8v0RECE/edit#slide=id.g333298d27a_0_494

**Comment by zheileman** [comment]
This is not for PILOT. We are screening out urgent applications, so this step is not implemented in the Rails app! However the address will be shown in the screener.

**Comment by solidgoldpig** [comment]
@zheileman it's tagged public beta ;)
