### ISSUE TITLE
Adjust styling so that child option does not feel separated from the parent option

### ISSUE THREAD

**Issue by A-Millar** [ministryofjustice/c100-application#228]
The line only starts from where the element ends, which is in keeping with GDS style.

I think we need to either:
- tweak the padding, to bring the child option up
- extend the line 

![bug 2](https://user-images.githubusercontent.com/24225467/36532474-c045ee38-17b8-11e8-9353-db2fad03158e.png)

**Comment by zheileman** [comment]
Fixed in #235
